version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: Datad0g1
      POSTGRES_USER: pguser
      POSTGRES_DB: resumeData
    ports:
      - 5432:5432
